#ex1:
number1=input("enter number1:")
number2=input("enter number2:")
sume=float(number1)+float(number2)
print(sume)
sub=float(number1)-float(number2)
print(sub)
mul=float(number1)*float(number2)
print(mul)
div=float(number1)/float(number2)
print(div)
mood=float(number1)%float(number2)
print(mood)
expon=float(number1)**float(number2)
print(expon)
ddfloor=float(number1)//float(number2)
print(ddfloor)